/** Catalog aligned with storefront (slugs stable for URLs). */
module.exports = [
  { name: 'Clarks Gereld Tie', slug: 'clarks-gereld-tie', brandName: 'Clarks', categorySlug: 'shoes', price: 32500, featured: true, description: 'Classic derby with premium leather.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.12 PM.jpeg', colors: ['Black Leather', 'Dark Brown Leather', 'Tan Leather'] },
  { name: 'Santoni Leather Loafers', slug: 'santoni-leather-loafers', brandName: 'Santoni', categorySlug: 'shoes', price: 85000, featured: true, description: 'Italian handcrafted loafers.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.21 PM.jpeg', colors: ['Black Leather', 'Navy Blue Leather', 'Dark Brown Leather'] },
  { name: 'Santoni Slip-on Loafers', slug: 'santoni-slip-on-loafers', brandName: 'Santoni', categorySlug: 'shoes', price: 78000, featured: false, description: 'Sleek slip-on loafers.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.25 PM.jpeg', colors: ['Black Leather', 'Dark Brown Leather'] },
  { name: 'Prada Tracksuit Ensemble', slug: 'prada-tracksuit-ensemble', brandName: 'Prada', categorySlug: 'tracksuits', price: 145000, featured: true, description: 'Luxury athletic wear.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.17 PM.jpeg', colors: ['Prada Black'] },
  { name: 'Stefano Ricci Tracksuit', slug: 'stefano-ricci-tracksuit', brandName: 'Stefano Ricci', categorySlug: 'tracksuits', price: 185000, featured: true, description: 'Silk and cotton blend tracksuit.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.18 PM.jpeg', colors: ['Dark Green'] },
  { name: 'Dockers Tapered Fit Pants', slug: 'dockers-tapered-fit-pants', brandName: 'Dockers', categorySlug: 'trousers', price: 22000, featured: false, description: 'Modern tapered chinos.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.20 PM.jpeg', colors: ['Sandstone', 'Navy Blue', 'Steel Grey'] },
  { name: 'Presidential Luxury Shirt', slug: 'presidential-luxury-shirt', brandName: 'Presidential', categorySlug: 'shirts', price: 28000, featured: true, description: 'Premium patterned shirts.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.30 PM.jpeg', colors: ['Blue Paisley', 'Grey Paisley', 'Green Patterned', 'Checked'] },
  { name: 'Santoni Double Monk-Strap', slug: 'santoni-double-monk-strap', brandName: 'Santoni', categorySlug: 'shoes', price: 92000, featured: true, description: 'Double monk-strap dress shoes.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.37 PM.jpeg', colors: ['Dark Brown Leather', 'Grey Suede'] },
  { name: 'Clarks Luxury Loafers', slug: 'clarks-luxury-loafers', brandName: 'Clarks', categorySlug: 'shoes', price: 34500, featured: false, description: 'Refined loafers with hardware.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.39 PM.jpeg', colors: ['Black Penny Loafers', 'Dark Brown Bit Loafers', 'Navy Blue Bit Loafers', 'Black Bit Loafers'] },
  { name: 'Clarks Premium Oxford', slug: 'clarks-premium-oxford', brandName: 'Clarks', categorySlug: 'shoes', price: 36000, featured: true, description: 'Cap-toe and wingtip oxfords.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.42 PM.jpeg', colors: ['Black Cap-Toe', 'Dark Brown Cap-Toe', 'Black Wingtip Brogue', 'Dark Brown Wingtip', 'Tan Wingtip'] },
  { name: 'Black Puffer Vest', slug: 'black-puffer-vest', brandName: 'Boutique', categorySlug: 'outerwear', price: 45000, featured: false, description: 'Lightweight insulated vest.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.33 PM.jpeg', colors: ['Midnight Black'] },
  { name: 'Zegna Luxury Tracksuit', slug: 'zegna-luxury-tracksuit', brandName: 'Zegna', categorySlug: 'tracksuits', price: 195000, featured: true, description: 'Wool and cashmere blend.', thumbnail: '/WhatsApp Image 2026-05-12 at 8.07.17 PM (1).jpeg', colors: ['Zegna Signature'] },
];
