// NEW — Stock catalog from Prince Esquire Stock.xlsx
module.exports = [
  { name: 'Shirts', opening: 600, sales: 10, stockOut: 0, stockIn: 0, closing: 590 },
  { name: 'Khakis', opening: 540, sales: 12, stockOut: 0, stockIn: 0, closing: 528 },
  { name: 'Knitted Pollos', opening: 50, sales: 5, stockOut: 0, stockIn: 0, closing: 45 },
  { name: 'Polos', opening: 45, sales: 10, stockOut: 0, stockIn: 0, closing: 35 },
  { name: 'Office Shoes', opening: 56, sales: 4, stockOut: 0, stockIn: 0, closing: 52 },
  { name: 'Casual Shoes', opening: 42, sales: 7, stockOut: 0, stockIn: 0, closing: 35 },
  { name: 'Loafers', opening: 30, sales: 40, stockOut: 0, stockIn: 0, closing: 0 },
  { name: 'Linen Trousers', opening: 60, sales: 4, stockOut: 0, stockIn: 0, closing: 56 },
  { name: 'Blazers', opening: 31, sales: 7, stockOut: 0, stockIn: 0, closing: 24 },
  { name: 'Suits', opening: 40, sales: 8, stockOut: 0, stockIn: 0, closing: 32 },
  { name: 'Track Suits', opening: 51, sales: 7, stockOut: 0, stockIn: 0, closing: 44 },
  { name: 'Vests', opening: 4, sales: 9, stockOut: 0, stockIn: 0, closing: 0 },
  { name: 'Capes', opening: 12, sales: 0, stockOut: 0, stockIn: 0, closing: 12 },
  { name: 'Hats', opening: 3, sales: 0, stockOut: 0, stockIn: 0, closing: 3 },
  { name: 'Ties', opening: 4, sales: 2, stockOut: 0, stockIn: 0, closing: 2 },
  { name: 'Belts', opening: 13, sales: 4, stockOut: 0, stockIn: 0, closing: 9 },
  { name: 'Jackets', opening: 31, sales: 1, stockOut: 0, stockIn: 0, closing: 30 },
  { name: 'Half-Jackets', opening: 17, sales: 3, stockOut: 0, stockIn: 0, closing: 14 },
  { name: 'Sweat Shirts', opening: 23, sales: 0, stockOut: 0, stockIn: 0, closing: 23 },
  { name: 'Socks', opening: 3, sales: 6, stockOut: 0, stockIn: 0, closing: 0 },
  { name: 'Sweaters', opening: 42, sales: 0, stockOut: 0, stockIn: 0, closing: 42 },
  { name: 'Jeans', opening: 21, sales: 0, stockOut: 0, stockIn: 0, closing: 21 },
  { name: 'T-Shirts', opening: 31, sales: 0, stockOut: 0, stockIn: 0, closing: 31 },
  { name: 'Gurkha Pants', opening: 30, sales: 0, stockOut: 0, stockIn: 0, closing: 30 },
];
