-- Auto-generated from src/assets and src/assets/catalog.
-- Ensures all image-based products are available in DB and manageable in admin.

begin;

with category_rows(slug, name, description, image_url) as (
  values
  ('belts', 'Belts', null, null),
  ('casual', 'Casual', null, null),
  ('formal', 'Formal', null, null),
  ('khaki-pants', 'Khaki Pants', null, null),
  ('shirts', 'Shirts', null, null),
  ('shoes', 'Shoes', null, null),
  ('socks', 'Socks', null, null),
  ('sportswear', 'Sportswear', null, null),
  ('suits', 'Suits', null, null),
  ('t-shirts', 'T Shirts', null, null),
  ('track-suits', 'Track Suits', null, null),
  ('trousers', 'Trousers', null, null)
)
insert into public.categories (slug, name, description, image_url)
select slug, name, description, image_url
from category_rows
on conflict (slug) do update
set name = excluded.name;

with product_rows(slug, title, description, category_slug, price, is_published, is_featured) as (
  values
  ('belts-1-belt-2-colors-pay-for-one-belt-but-get-two', '1 Belt 2 Colors Pay For One Belt But Get Two', '1 Belt 2 Colors Pay For One Belt But Get Two', 'belts', 2000, true, false),
  ('belts-1-belt-2-colors-smart-brown-on-one-side-classic', '1 Belt 2 Colors Smart Brown On One Side Classic', '1 Belt 2 Colors Smart Brown On One Side Classic', 'belts', 4000, true, false),
  ('belts-always-fit-this-woven-stretch-braided-belt-enable', 'Always Fit This Woven Stretch Braided Belt Enable', 'Always Fit This Woven Stretch Braided Belt Enable', 'belts', 1500, true, false),
  ('belts-antique-metal-buckle-cowhide-leather-belt-crafted', 'Antique Metal Buckle Cowhide Leather Belt Crafted', 'Antique Metal Buckle Cowhide Leather Belt Crafted', 'belts', 2000, true, false),
  ('belts-brand-lcg-luchengyi-buckle-material-alloy', 'Brand Lcg Luchengyi Buckle Material Alloy', 'Brand Lcg Luchengyi Buckle Material Alloy', 'belts', 2000, true, false),
  ('belts-brand-name-kavenpeterdepartment-name-adultbelts', 'Brand Name Kavenpeterdepartment Name Adultbelts', 'Brand Name Kavenpeterdepartment Name Adultbelts', 'belts', 2000, true, false),
  ('belts-cat-belts', 'Belts', 'Belts', 'belts', 1500, true, false),
  ('belts-cowather', 'Cowather', 'Cowather', 'belts', 1500, true, false),
  ('belts-custom-size-fit-never-worry-about-the-belt-being', 'Custom Size Fit Never Worry About The Belt Being', 'Custom Size Fit Never Worry About The Belt Being', 'belts', 4500, true, false),
  ('belts-embossed-western-cowboy-thick-belt-crafted-from', 'Embossed Western Cowboy Thick Belt Crafted From', 'Embossed Western Cowboy Thick Belt Crafted From', 'belts', 4000, true, false),
  ('belts-exact-fit-micro-adjustment-of-0-25-ensure-a', 'Exact Fit Micro Adjustment Of 0 25 Ensure A', 'Exact Fit Micro Adjustment Of 0 25 Ensure A', 'belts', 4000, true, false),
  ('belts-for-exact-fit-leather-belts-for-men-allows-for', 'For Exact Fit Leather Belts For Men Allows For', 'For Exact Fit Leather Belts For Men Allows For', 'belts', 3000, true, false),
  ('belts-genuine-leather-belt-exaxt-fit-by-cutting-for-2', 'Genuine Leather Belt Exaxt Fit By Cutting For 2', 'Genuine Leather Belt Exaxt Fit By Cutting For 2', 'belts', 2500, true, false),
  ('belts-genuine-leather-belt-exaxt-fit-by-cutting-for', 'Genuine Leather Belt Exaxt Fit By Cutting For', 'Genuine Leather Belt Exaxt Fit By Cutting For', 'belts', 1500, true, false),
  ('belts-introducing-designers-casual-patchwork-men-belts', 'Introducing Designers Casual Patchwork Men Belts', 'Introducing Designers Casual Patchwork Men Belts', 'belts', 3500, true, false),
  ('belts-item', 'Item', 'Item', 'belts', 1500, true, false),
  ('belts-levi-s-men-s-leather-belt-with-plaque-buckle', 'Levi S Men S Leather Belt With Plaque Buckle', 'Levi S Men S Leather Belt With Plaque Buckle', 'belts', 3000, true, false),
  ('belts-luxury-designer-34mm-belts-men-high-quality-canvas', 'Luxury Designer 34mm Belts Men High Quality Canvas', 'Luxury Designer 34mm Belts Men High Quality Canvas', 'belts', 3500, true, false),
  ('belts-new-width-3-4cm-men-s-belt-business-formal-real', 'New Width 3 4cm Men S Belt Business Formal Real', 'New Width 3 4cm Men S Belt Business Formal Real', 'belts', 2000, true, false),
  ('belts-premium-leather-the-kemisant-men-golf-belt-is', 'Premium Leather The Kemisant Men Golf Belt Is', 'Premium Leather The Kemisant Men Golf Belt Is', 'belts', 2000, true, false),
  ('belts-premium-quality-100-pure-genuine-leather-belt', 'Premium Quality 100 Pure Genuine Leather Belt', 'Premium Quality 100 Pure Genuine Leather Belt', 'belts', 1500, true, false),
  ('belts-specificationsbelt-width-4-3belts-material', 'Specificationsbelt Width 4 3belts Material', 'Specificationsbelt Width 4 3belts Material', 'belts', 1500, true, false),
  ('belts-this-classic-men-s-brown-leather-belt-is-crafted', 'This Classic Men S Brown Leather Belt Is Crafted', 'This Classic Men S Brown Leather Belt Is Crafted', 'belts', 3000, true, false),
  ('belts-top-genuine-leather-and-cowhide-material-men-s', 'Top Genuine Leather And Cowhide Material Men S', 'Top Genuine Leather And Cowhide Material Men S', 'belts', 1500, true, false),
  ('khaki-pants-amazon-com-lapg-men-s-core-cargo-tactical-pants-2', 'Amazon Com Lapg Men S Core Cargo Tactical Pants 2', 'Amazon Com Lapg Men S Core Cargo Tactical Pants 2', 'khaki-pants', 5000, true, false),
  ('khaki-pants-amazon-com-lapg-men-s-core-cargo-tactical-pants', 'Amazon Com Lapg Men S Core Cargo Tactical Pants', 'Amazon Com Lapg Men S Core Cargo Tactical Pants', 'khaki-pants', 7500, true, false),
  ('khaki-pants-cargohose-herren-fruhling-herbst-baumwolle', 'Cargohose Herren Fruhling Herbst Baumwolle', 'Cargohose Herren Fruhling Herbst Baumwolle', 'khaki-pants', 8500, true, false),
  ('khaki-pants-everyones-favorite-mens-casual-cargo-shorts', 'Everyones Favorite Mens Casual Cargo Shorts', 'Everyones Favorite Mens Casual Cargo Shorts', 'khaki-pants', 8500, true, false),
  ('khaki-pants-men-s-cargo-shorts-shorts-leg-drawstring-6-pocket', 'Men S Cargo Shorts Shorts Leg Drawstring 6 Pocket', 'Men S Cargo Shorts Shorts Leg Drawstring 6 Pocket', 'khaki-pants', 6500, true, false),
  ('khaki-pants-men-s-totem-shirt-button-up-shirt-long-sleeve-vintage-gothic-outdoor-h', 'Men S Totem Shirt Button Up Shirt Long Sleeve Vintage Gothic Outdoor H', 'Men S Totem Shirt Button Up Shirt Long Sleeve Vintage Gothic Outdoor H', 'khaki-pants', 5000, true, false),
  ('khaki-pants-short-de-travail-elastique-multi-poches-style', 'Short De Travail Elastique Multi Poches Style', 'Short De Travail Elastique Multi Poches Style', 'khaki-pants', 8000, true, false),
  ('khaki-pants-the-all-season-tactical-pants-deliver-top-tier', 'The All Season Tactical Pants Deliver Top Tier', 'The All Season Tactical Pants Deliver Top Tier', 'khaki-pants', 8000, true, false),
  ('khaki-pants-these-easygoing-chinos-are-a-great-alternative-to', 'These Easygoing Chinos Are A Great Alternative To', 'These Easygoing Chinos Are A Great Alternative To', 'khaki-pants', 5500, true, false),
  ('shirts-bring-a-burst-of-colours-to-your-spring-wardrobe', 'Bring A Burst Of Colours To Your Spring Wardrobe', 'Bring A Burst Of Colours To Your Spring Wardrobe', 'shirts', 5000, true, false),
  ('shirts-bubblems', 'Bubblems', 'Bubblems', 'shirts', 4000, true, false),
  ('shirts-chemise-en-denim-corentm-la-force-masculine', 'Chemise En Denim Corentm La Force Masculine', 'Chemise En Denim Corentm La Force Masculine', 'shirts', 5500, true, false),
  ('shirts-coofandy-men-s-dress-shirt-long-sleeve-casual-button-down-shirts', 'Coofandy Men S Dress Shirt Long Sleeve Casual Button Down Shirts', 'Coofandy Men S Dress Shirt Long Sleeve Casual Button Down Shirts', 'shirts', 4000, true, false),
  ('shirts-download-12', 'Download 12', 'Download 12', 'shirts', 5500, true, false),
  ('shirts-download', 'Download', 'Download', 'shirts', 5500, true, false),
  ('shirts-floral-print-dress-hirt-1-piece', 'Floral Print Dress Hirt 1 Piece', 'Floral Print Dress Hirt 1 Piece', 'shirts', 6000, true, false),
  ('shirts-laurent-monaco-chemise-decouvrez-un-nouvel', 'Laurent Monaco Chemise Decouvrez Un Nouvel', 'Laurent Monaco Chemise Decouvrez Un Nouvel', 'shirts', 3500, true, false),
  ('shirts-laurent-monaco-chemise-rayee-pour-homme', 'Laurent Monaco Chemise Rayee Pour Homme', 'Laurent Monaco Chemise Rayee Pour Homme', 'shirts', 5500, true, false),
  ('shirts-material-polyester-fibershirts-type-casual', 'Material Polyester Fibershirts Type Casual', 'Material Polyester Fibershirts Type Casual', 'shirts', 6000, true, false),
  ('shirts-men-pleated-decoration-button-up-shirt', 'Men Pleated Decoration Button Up Shirt', 'Men Pleated Decoration Button Up Shirt', 'shirts', 3500, true, false),
  ('shirts-men-s-dress-shirt-black-red-black-gray-sea', 'Men S Dress Shirt Black Red Black Gray Sea', 'Men S Dress Shirt Black Red Black Gray Sea', 'shirts', 4500, true, false),
  ('shirts-men-s-dress-shirt-striped-shirt-button-down-shirt', 'Men S Dress Shirt Striped Shirt Button Down Shirt', 'Men S Dress Shirt Striped Shirt Button Down Shirt', 'shirts', 3500, true, false),
  ('shirts-men-s-shirt-dress-shirt-button-up-shirt-black-white-wine-royal-blue-lo', 'Men S Shirt Dress Shirt Button Up Shirt Black White Wine Royal Blue Lo', 'Men S Shirt Dress Shirt Button Up Shirt Black White Wine Royal Blue Lo', 'shirts', 3000, true, false),
  ('shirts-morintm-polo-raye-classique-moderne', 'Morintm Polo Raye Classique Moderne', 'Morintm Polo Raye Classique Moderne', 'shirts', 5500, true, false),
  ('shirts-oliver-long-sleeve-high-gloss-shirt', 'Oliver Long Sleeve High Gloss Shirt', 'Oliver Long Sleeve High Gloss Shirt', 'shirts', 3000, true, false),
  ('shirts-prices-may-vary-100-polyester-button-closure-the-2', 'Prices May Vary 100 Polyester Button Closure The 2', 'Prices May Vary 100 Polyester Button Closure The 2', 'shirts', 3500, true, false),
  ('shirts-prices-may-vary-100-polyester-button-closure-the-3', 'Prices May Vary 100 Polyester Button Closure The 3', 'Prices May Vary 100 Polyester Button Closure The 3', 'shirts', 4000, true, false),
  ('shirts-prices-may-vary-100-polyester-button-closure-the-4', 'Prices May Vary 100 Polyester Button Closure The 4', 'Prices May Vary 100 Polyester Button Closure The 4', 'shirts', 4500, true, false),
  ('shirts-prices-may-vary-100-polyester-button-closure-the-5', 'Prices May Vary 100 Polyester Button Closure The 5', 'Prices May Vary 100 Polyester Button Closure The 5', 'shirts', 5000, true, false),
  ('shirts-prices-may-vary-100-polyester-button-closure-the', 'Prices May Vary 100 Polyester Button Closure The', 'Prices May Vary 100 Polyester Button Closure The', 'shirts', 3500, true, false),
  ('shirts-prices-may-vary-100-polyester-button-closure', 'Prices May Vary 100 Polyester Button Closure', 'Prices May Vary 100 Polyester Button Closure', 'shirts', 5500, true, false),
  ('shirts-prices-may-vary-high-quality-fabricthe-men', 'Prices May Vary High Quality Fabricthe Men', 'Prices May Vary High Quality Fabricthe Men', 'shirts', 5000, true, false),
  ('shirts-prices-may-vary-polyester-65-viscose-35-button', 'Prices May Vary Polyester 65 Viscose 35 Button', 'Prices May Vary Polyester 65 Viscose 35 Button', 'shirts', 3500, true, false),
  ('shirts-product-id-4001153086977', 'Product Id 4001153086977', 'Product Id 4001153086977', 'shirts', 3500, true, false),
  ('shirts-red-collar-fabric-embellished-men', 'Red Collar Fabric Embellished Men', 'Red Collar Fabric Embellished Men', 'shirts', 5000, true, false),
  ('shirts-rossi-roma-poloshirt-in-grobstrick-beige-3xl', 'Rossi Roma Poloshirt In Grobstrick Beige 3xl', 'Rossi Roma Poloshirt In Grobstrick Beige 3xl', 'shirts', 4500, true, false),
  ('shirts-zeroyaa-men-s-hipster-african-tribal-graphic-patchwork-design-slim-fit', 'Zeroyaa Men S Hipster African Tribal Graphic Patchwork Design Slim Fit', 'Zeroyaa Men S Hipster African Tribal Graphic Patchwork Design Slim Fit', 'shirts', 3500, true, false),
  ('shoes-cat-shoes', 'Shoes', 'Shoes', 'shoes', 10000, true, false),
  ('shoes-classic-leather-dress-shoes-for-men', 'Classic Leather Dress Shoes For Men', 'Classic Leather Dress Shoes For Men', 'shoes', 10000, true, false),
  ('shoes-download-10', 'Download 10', 'Download 10', 'shoes', 16000, true, false),
  ('shoes-download-11', 'Download 11', 'Download 11', 'shoes', 16500, true, false),
  ('shoes-download-2', 'Download 2', 'Download 2', 'shoes', 16500, true, false),
  ('shoes-download-4', 'Download 4', 'Download 4', 'shoes', 17500, true, false),
  ('shoes-download-5', 'Download 5', 'Download 5', 'shoes', 18000, true, false),
  ('shoes-download-6', 'Download 6', 'Download 6', 'shoes', 10000, true, false),
  ('shoes-download-7', 'Download 7', 'Download 7', 'shoes', 10500, true, false),
  ('shoes-download-8', 'Download 8', 'Download 8', 'shoes', 11000, true, false),
  ('shoes-download-9', 'Download 9', 'Download 9', 'shoes', 11500, true, false),
  ('shoes-herren-sport-jogging-schuhe-hip-hop-jogging', 'Herren Sport Jogging Schuhe Hip Hop Jogging', 'Herren Sport Jogging Schuhe Hip Hop Jogging', 'shoes', 16000, true, false),
  ('shoes-ky', 'Ky', 'Ky', 'shoes', 16000, true, false),
  ('shoes-luxury-men-leather-loafers-designer-tassels-brogue', 'Luxury Men Leather Loafers Designer Tassels Brogue', 'Luxury Men Leather Loafers Designer Tassels Brogue', 'shoes', 16500, true, false),
  ('shoes-men-s-colorful-pattern-design-loafers-with-shiny-elements-low-cut-slip', 'Men S Colorful Pattern Design Loafers With Shiny Elements Low Cut Slip', 'Men S Colorful Pattern Design Loafers With Shiny Elements Low Cut Slip', 'shoes', 17500, true, false),
  ('shoes-shoes', 'Shoes', 'Shoes', 'shoes', 12000, true, false),
  ('shoes-stand-tall-stay-bold-the-chunky-heel', 'Stand Tall Stay Bold The Chunky Heel', 'Stand Tall Stay Bold The Chunky Heel', 'shoes', 10000, true, false),
  ('shoes-temu-best-deals', 'Temu Best Deals', 'Temu Best Deals', 'shoes', 14000, true, false),
  ('shoes-the-first-step-to-perfection-shoes', 'The First Step To Perfection Shoes', 'The First Step To Perfection Shoes', 'shoes', 11500, true, false),
  ('shoes-this-item-is-unavailable-etsy', 'This Item Is Unavailable Etsy', 'This Item Is Unavailable Etsy', 'shoes', 11000, true, false),
  ('socks-a-must-have-addition-to-every-man-s-winter', 'A Must Have Addition To Every Man S Winter', 'A Must Have Addition To Every Man S Winter', 'socks', 1500, true, false),
  ('socks-best-socks-for-men-shop-for-mens-socks-online', 'Best Socks For Men Shop For Mens Socks Online', 'Best Socks For Men Shop For Mens Socks Online', 'socks', 500, true, false),
  ('socks-cat-socks-2', 'Socks 2', 'Socks 2', 'socks', 1000, true, false),
  ('socks-hippih-5-pairs-men-dress-socks-cotton-argyle', 'Hippih 5 Pairs Men Dress Socks Cotton Argyle', 'Hippih 5 Pairs Men Dress Socks Cotton Argyle', 'socks', 1000, true, false),
  ('socks-multicolorido-collar-tecido-simples-meias-de', 'Multicolorido Collar Tecido Simples Meias De', 'Multicolorido Collar Tecido Simples Meias De', 'socks', 1000, true, false),
  ('socks-qcwqmyl-men-s-grip-soccer-socks-anti-slip-hospital', 'Qcwqmyl Men S Grip Soccer Socks Anti Slip Hospital', 'Qcwqmyl Men S Grip Soccer Socks Anti Slip Hospital', 'socks', 500, true, false),
  ('socks-quality-materials-dress-socks-made-with-fine', 'Quality Materials Dress Socks Made With Fine', 'Quality Materials Dress Socks Made With Fine', 'socks', 500, true, false),
  ('suits-attirez-lattention-deplacez-vous-avec-assurance', 'Attirez Lattention Deplacez Vous Avec Assurance', 'Attirez Lattention Deplacez Vous Avec Assurance', 'suits', 40500, true, false),
  ('suits-black-mandarin-collar-suit-gentleman-s-guru-2', 'Black Mandarin Collar Suit Gentleman S Guru 2', 'Black Mandarin Collar Suit Gentleman S Guru 2', 'suits', 28000, true, false),
  ('suits-black-mandarin-collar-suit-gentleman-s-guru', 'Black Mandarin Collar Suit Gentleman S Guru', 'Black Mandarin Collar Suit Gentleman S Guru', 'suits', 28000, true, false),
  ('suits-brown-houndstooth-3-piece-suit-for-men-double-2', 'Brown Houndstooth 3 Piece Suit For Men Double 2', 'Brown Houndstooth 3 Piece Suit For Men Double 2', 'suits', 32500, true, false),
  ('suits-brown-houndstooth-3-piece-suit-for-men-double-3', 'Brown Houndstooth 3 Piece Suit For Men Double 3', 'Brown Houndstooth 3 Piece Suit For Men Double 3', 'suits', 33000, true, false),
  ('suits-brown-houndstooth-3-piece-suit-for-men-double', 'Brown Houndstooth 3 Piece Suit For Men Double', 'Brown Houndstooth 3 Piece Suit For Men Double', 'suits', 40000, true, false),
  ('suits-cat-formal', 'Formal', 'Formal', 'suits', 26000, true, false),
  ('suits-cat-suits', 'Suits', 'Suits', 'suits', 22000, true, false),
  ('suits-choose-timeless-elegance-with-the-men-s-leather', 'Choose Timeless Elegance With The Men S Leather', 'Choose Timeless Elegance With The Men S Leather', 'suits', 18000, true, false),
  ('suits-decouvrez-l-elegance-avec-le-modele-aaron-une', 'Decouvrez L Elegance Avec Le Modele Aaron Une', 'Decouvrez L Elegance Avec Le Modele Aaron Une', 'suits', 38000, true, false),
  ('suits-description-formal-men-s-suits-2-piece-slim-fit', 'Description Formal Men S Suits 2 Piece Slim Fit', 'Description Formal Men S Suits 2 Piece Slim Fit', 'suits', 29500, true, false),
  ('suits-discover-aryan-dark-navy-three-pieces-close', 'Discover Aryan Dark Navy Three Pieces Close', 'Discover Aryan Dark Navy Three Pieces Close', 'suits', 26500, true, false),
  ('suits-discover-the-pinnacle-of-ready-to-wear-fashion', 'Discover The Pinnacle Of Ready To Wear Fashion', 'Discover The Pinnacle Of Ready To Wear Fashion', 'suits', 44000, true, false),
  ('suits-discover-the-very-best-kent-dark-green-3-pieces', 'Discover The Very Best Kent Dark Green 3 Pieces', 'Discover The Very Best Kent Dark Green 3 Pieces', 'suits', 33500, true, false),
  ('suits-elegance-tailored-with-intention-army-green-meets', 'Elegance Tailored With Intention Army Green Meets', 'Elegance Tailored With Intention Army Green Meets', 'suits', 43000, true, false),
  ('suits-elevate-your-formal-style-with-this-luxurious', 'Elevate Your Formal Style With This Luxurious', 'Elevate Your Formal Style With This Luxurious', 'suits', 37000, true, false),
  ('suits-formal-men-s-suits-2-piece-slim-fit-performance', 'Formal Men S Suits 2 Piece Slim Fit Performance', 'Formal Men S Suits 2 Piece Slim Fit Performance', 'suits', 38000, true, false),
  ('suits-formelle-bekleidung-fur-besondere-anlasse', 'Formelle Bekleidung Fur Besondere Anlasse', 'Formelle Bekleidung Fur Besondere Anlasse', 'suits', 35000, true, false),
  ('suits-hero-suit', 'Suit', 'Suit', 'suits', 43500, true, false),
  ('suits-instagram-2', 'Instagram 2', 'Instagram 2', 'suits', 45000, true, false),
  ('suits-jacket-regular-fit-single-breasted-notch', 'Jacket Regular Fit Single Breasted Notch', 'Jacket Regular Fit Single Breasted Notch', 'suits', 40500, true, false),
  ('suits-laurent-monaco-structure-sur-mesure-elegance', 'Laurent Monaco Structure Sur Mesure Elegance', 'Laurent Monaco Structure Sur Mesure Elegance', 'suits', 38000, true, false),
  ('suits-looks-like-something-from-a-final-fantasy', 'Looks Like Something From A Final Fantasy', 'Looks Like Something From A Final Fantasy', 'suits', 39500, true, false),
  ('suits-make-a-lasting-impression-with-this-men-s-slim-fit', 'Make A Lasting Impression With This Men S Slim Fit', 'Make A Lasting Impression With This Men S Slim Fit', 'suits', 37500, true, false),
  ('suits-men-s-grey-double-breasted-suit-timeless', 'Men S Grey Double Breasted Suit Timeless', 'Men S Grey Double Breasted Suit Timeless', 'suits', 41500, true, false),
  ('suits-men-s-suits-slim-fit-3-pieces-notch-lapel-formal-2', 'Men S Suits Slim Fit 3 Pieces Notch Lapel Formal 2', 'Men S Suits Slim Fit 3 Pieces Notch Lapel Formal 2', 'suits', 26500, true, false),
  ('suits-men-s-suits-slim-fit-3-pieces-notch-lapel-formal', 'Men S Suits Slim Fit 3 Pieces Notch Lapel Formal', 'Men S Suits Slim Fit 3 Pieces Notch Lapel Formal', 'suits', 24000, true, false),
  ('suits-men-tie-sets-classic-fashion-necktie-set-with', 'Men Tie Sets Classic Fashion Necktie Set With', 'Men Tie Sets Classic Fashion Necktie Set With', 'suits', 37500, true, false),
  ('suits-mens-premium-black-2-piece-prom-suit-elegant-slim-fit-custom-wedding-g', 'Mens Premium Black 2 Piece Prom Suit Elegant Slim Fit Custom Wedding G', 'Mens Premium Black 2 Piece Prom Suit Elegant Slim Fit Custom Wedding G', 'suits', 43000, true, false),
  ('suits-prices-may-vary-free-customizationcheck-out-the', 'Prices May Vary Free Customizationcheck Out The', 'Prices May Vary Free Customizationcheck Out The', 'suits', 21500, true, false),
  ('suits-redefine-morden-tailoring-with-this-two-tone', 'Redefine Morden Tailoring With This Two Tone', 'Redefine Morden Tailoring With This Two Tone', 'suits', 37500, true, false),
  ('suits-refined-timeless-and-effortlessly-elegant', 'Refined Timeless And Effortlessly Elegant', 'Refined Timeless And Effortlessly Elegant', 'suits', 44500, true, false),
  ('suits-rockefeller-collection-double-breasted-stripe', 'Rockefeller Collection Double Breasted Stripe', 'Rockefeller Collection Double Breasted Stripe', 'suits', 29000, true, false),
  ('suits-royal-blue-tuxedo-with-black-lapel-gentleman-s', 'Royal Blue Tuxedo With Black Lapel Gentleman S', 'Royal Blue Tuxedo With Black Lapel Gentleman S', 'suits', 39000, true, false),
  ('suits-step-into-timeless-elegance-with-this-men-s-navy', 'Step Into Timeless Elegance With This Men S Navy', 'Step Into Timeless Elegance With This Men S Navy', 'suits', 42500, true, false),
  ('suits-this-garment-portrays-all-the-original-styling-of', 'This Garment Portrays All The Original Styling Of', 'This Garment Portrays All The Original Styling Of', 'suits', 41000, true, false),
  ('suits-top-offer-of-the-season-men-s-luxury-designer', 'Top Offer Of The Season Men S Luxury Designer', 'Top Offer Of The Season Men S Luxury Designer', 'suits', 21000, true, false),
  ('suits-upgrade-your-professional-wardrobe-with-our-men-s', 'Upgrade Your Professional Wardrobe With Our Men S', 'Upgrade Your Professional Wardrobe With Our Men S', 'suits', 18500, true, false),
  ('suits-vintage-plaid-tweed-three-pieces-suit-elevate-your', 'Vintage Plaid Tweed Three Pieces Suit Elevate Your', 'Vintage Plaid Tweed Three Pieces Suit Elevate Your', 'suits', 27500, true, false),
  ('suits-wangyue-men-s-chinese-tunic-suit-stand-collar-slim', 'Wangyue Men S Chinese Tunic Suit Stand Collar Slim', 'Wangyue Men S Chinese Tunic Suit Stand Collar Slim', 'suits', 24500, true, false),
  ('t-shirts-black-casual-collar-short-sleeve', 'Black Casual Collar Short Sleeve', 'Black Casual Collar Short Sleeve', 't-shirts', 3000, true, false),
  ('t-shirts-casual-top-from-build-your-brand-comfortable', 'Casual Top From Build Your Brand Comfortable', 'Casual Top From Build Your Brand Comfortable', 't-shirts', 3500, true, false),
  ('t-shirts-cat-casual', 'Casual', 'Casual', 't-shirts', 1500, true, false),
  ('t-shirts-cat-shirts', 'Shirts', 'Shirts', 't-shirts', 2000, true, false),
  ('t-shirts-category-t-shirt-season-summer-fabric-100', 'Category T Shirt Season Summer Fabric 100', 'Category T Shirt Season Summer Fabric 100', 't-shirts', 2000, true, false),
  ('t-shirts-dm-for-size-m-l-xl-2xl-i-also-provide-custom-logo', 'Dm For Size M L Xl 2xl I Also Provide Custom Logo', 'Dm For Size M L Xl 2xl I Also Provide Custom Logo', 't-shirts', 3500, true, false),
  ('t-shirts-instagram', 'Instagram', 'Instagram', 't-shirts', 2000, true, false),
  ('t-shirts-men-allover-print-button-front-shirt', 'Men Allover Print Button Front Shirt', 'Men Allover Print Button Front Shirt', 't-shirts', 3500, true, false),
  ('t-shirts-men-argyle-print-shirt', 'Men Argyle Print Shirt', 'Men Argyle Print Shirt', 't-shirts', 1500, true, false),
  ('t-shirts-men-random-geo-print-shirt-without-tee-slim-fit', 'Men Random Geo Print Shirt Without Tee Slim Fit', 'Men Random Geo Print Shirt Without Tee Slim Fit', 't-shirts', 3000, true, false),
  ('t-shirts-men-slim-fit-shirt-long-sleeve-men-s-designer', 'Men Slim Fit Shirt Long Sleeve Men S Designer', 'Men Slim Fit Shirt Long Sleeve Men S Designer', 't-shirts', 3500, true, false),
  ('t-shirts-men-t-shirts-fit-crew-neck-short-sleeve-casual', 'Men T Shirts Fit Crew Neck Short Sleeve Casual', 'Men T Shirts Fit Crew Neck Short Sleeve Casual', 't-shirts', 1500, true, false),
  ('t-shirts-neo-chrome-panel-boxy-tee-t-shirt-all-size', 'Neo Chrome Panel Boxy Tee T Shirt All Size', 'Neo Chrome Panel Boxy Tee T Shirt All Size', 't-shirts', 2500, true, false),
  ('t-shirts-prices-may-vary-60-cotton-40-polyester', 'Prices May Vary 60 Cotton 40 Polyester', 'Prices May Vary 60 Cotton 40 Polyester', 't-shirts', 2500, true, false),
  ('t-shirts-ressentez-vous-bien-avec-un-style-quotidien-sans-2', 'Ressentez Vous Bien Avec Un Style Quotidien Sans 2', 'Ressentez Vous Bien Avec Un Style Quotidien Sans 2', 't-shirts', 3000, true, false),
  ('t-shirts-ressentez-vous-bien-avec-un-style-quotidien-sans', 'Ressentez Vous Bien Avec Un Style Quotidien Sans', 'Ressentez Vous Bien Avec Un Style Quotidien Sans', 't-shirts', 3000, true, false),
  ('t-shirts-stay-effortlessly-stylish-with-this-modern-color', 'Stay Effortlessly Stylish With This Modern Color', 'Stay Effortlessly Stylish With This Modern Color', 't-shirts', 3500, true, false),
  ('t-shirts-upgrade-your-everyday-style-with-our-premium-men-s', 'Upgrade Your Everyday Style With Our Premium Men S', 'Upgrade Your Everyday Style With Our Premium Men S', 't-shirts', 3500, true, false),
  ('t-shirts-veredeln-sie-ihre-freizeitoutfits-mit-dem', 'Veredeln Sie Ihre Freizeitoutfits Mit Dem', 'Veredeln Sie Ihre Freizeitoutfits Mit Dem', 't-shirts', 2000, true, false),
  ('track-suits-cat-sportswear', 'Sportswear', 'Sportswear', 'track-suits', 10000, true, false),
  ('track-suits-conjunto-de-agasalho-esportivo-masculino-com', 'Conjunto De Agasalho Esportivo Masculino Com', 'Conjunto De Agasalho Esportivo Masculino Com', 'track-suits', 7500, true, false),
  ('track-suits-deportivo-in-2022-designer-clothes-for-men-men', 'Deportivo In 2022 Designer Clothes For Men Men', 'Deportivo In 2022 Designer Clothes For Men Men', 'track-suits', 9000, true, false),
  ('track-suits-download-3', 'Download 3', 'Download 3', 'track-suits', 12000, true, false),
  ('track-suits-item-2', 'Item 2', 'Item 2', 'track-suits', 11000, true, false),
  ('track-suits-jawin-premium-waffle-tracksuit-hoodie-fabric', 'Jawin Premium Waffle Tracksuit Hoodie Fabric', 'Jawin Premium Waffle Tracksuit Hoodie Fabric', 'track-suits', 10000, true, false),
  ('track-suits-men-s-european-and-american-colorblock-hoodie', 'Men S European And American Colorblock Hoodie', 'Men S European And American Colorblock Hoodie', 'track-suits', 6500, true, false),
  ('track-suits-men-s-tracksuits-track-suits-sets-jogging-suits', 'Men S Tracksuits Track Suits Sets Jogging Suits', 'Men S Tracksuits Track Suits Sets Jogging Suits', 'track-suits', 11000, true, false),
  ('track-suits-mens-track-suits-2-piece-the-track-suit-consists', 'Mens Track Suits 2 Piece The Track Suit Consists', 'Mens Track Suits 2 Piece The Track Suit Consists', 'track-suits', 14000, true, false),
  ('track-suits-price-product-description-item', 'Price Product Description Item', 'Price Product Description Item', 'track-suits', 9500, true, false),
  ('track-suits-prices-may-vary-polyester-cotton-drawstring-2', 'Prices May Vary Polyester Cotton Drawstring 2', 'Prices May Vary Polyester Cotton Drawstring 2', 'track-suits', 11500, true, false),
  ('track-suits-prices-may-vary-polyester-cotton-drawstring', 'Prices May Vary Polyester Cotton Drawstring', 'Prices May Vary Polyester Cotton Drawstring', 'track-suits', 13500, true, false),
  ('track-suits-product-information-materials-90-polyester-10', 'Product Information Materials 90 Polyester 10', 'Product Information Materials 90 Polyester 10', 'track-suits', 8000, true, false),
  ('track-suits-season-winter-fall-fabric-polyester-sleeve', 'Season Winter Fall Fabric Polyester Sleeve', 'Season Winter Fall Fabric Polyester Sleeve', 'track-suits', 8500, true, false),
  ('track-suits-service-if-you-have-any-question-please-feel', 'Service If You Have Any Question Please Feel', 'Service If You Have Any Question Please Feel', 'track-suits', 6000, true, false),
  ('track-suits-shein', 'Shein', 'Shein', 'track-suits', 11000, true, false),
  ('track-suits-source-new-jogging-custom-track-suits-tracksuit', 'Source New Jogging Custom Track Suits Tracksuit', 'Source New Jogging Custom Track Suits Tracksuit', 'track-suits', 14000, true, false),
  ('track-suits-tbmpoy-size-m-men-s-tracksuit-athletic-sports', 'Tbmpoy Size M Men S Tracksuit Athletic Sports', 'Tbmpoy Size M Men S Tracksuit Athletic Sports', 'track-suits', 9500, true, false),
  ('track-suits-track-suits-for-men-set-full-zip-active-athletic', 'Track Suits For Men Set Full Zip Active Athletic', 'Track Suits For Men Set Full Zip Active Athletic', 'track-suits', 8500, true, false),
  ('track-suits-tracksuits-are-now-in-the-mainstream-fashion', 'Tracksuits Are Now In The Mainstream Fashion', 'Tracksuits Are Now In The Mainstream Fashion', 'track-suits', 7500, true, false),
  ('track-suits-women-s-zipper-sports-suit-athletic-tracksuit', 'Women S Zipper Sports Suit Athletic Tracksuit', 'Women S Zipper Sports Suit Athletic Tracksuit', 'track-suits', 7500, true, false),
  ('trousers-brand-name-icpansmodel-number-xk058material', 'Brand Name Icpansmodel Number Xk058material', 'Brand Name Icpansmodel Number Xk058material', 'trousers', 4000, true, false),
  ('trousers-casual-fashion-sweatshirts-jackets-pants-plus-size', 'Casual Fashion Sweatshirts Jackets Pants Plus Size', 'Casual Fashion Sweatshirts Jackets Pants Plus Size', 'trousers', 6500, true, false),
  ('trousers-cat-trousers', 'Trousers', 'Trousers', 'trousers', 7000, true, false),
  ('trousers-cedratm-classic-denim-jeans-appear-confident-with', 'Cedratm Classic Denim Jeans Appear Confident With', 'Cedratm Classic Denim Jeans Appear Confident With', 'trousers', 4500, true, false),
  ('trousers-classic-fit-generous-fit-through-the-hip-and', 'Classic Fit Generous Fit Through The Hip And', 'Classic Fit Generous Fit Through The Hip And', 'trousers', 7000, true, false),
  ('trousers-fiabilite-quotidienne-les-pantalons-ferraro-en', 'Fiabilite Quotidienne Les Pantalons Ferraro En', 'Fiabilite Quotidienne Les Pantalons Ferraro En', 'trousers', 4500, true, false),
  ('trousers-jeans-men-new-men-s-fashion-business-jeans-classic', 'Jeans Men New Men S Fashion Business Jeans Classic', 'Jeans Men New Men S Fashion Business Jeans Classic', 'trousers', 7500, true, false),
  ('trousers-mens-cotton-blend-waffle-trousers-straight', 'Mens Cotton Blend Waffle Trousers Straight', 'Mens Cotton Blend Waffle Trousers Straight', 'trousers', 7500, true, false),
  ('trousers-mens-formal-wear-trousers-plain-colours-by-cavani-2', 'Mens Formal Wear Trousers Plain Colours By Cavani 2', 'Mens Formal Wear Trousers Plain Colours By Cavani 2', 'trousers', 5500, true, false),
  ('trousers-mens-formal-wear-trousers-plain-colours-by-cavani', 'Mens Formal Wear Trousers Plain Colours By Cavani', 'Mens Formal Wear Trousers Plain Colours By Cavani', 'trousers', 4500, true, false),
  ('trousers-mens-summer-suit-pants-thin-elastic-straight', 'Mens Summer Suit Pants Thin Elastic Straight', 'Mens Summer Suit Pants Thin Elastic Straight', 'trousers', 5000, true, false),
  ('trousers-okonkwo-style-americain-vintage-pantalon-militaire', 'Okonkwo Style Americain Vintage Pantalon Militaire', 'Okonkwo Style Americain Vintage Pantalon Militaire', 'trousers', 6500, true, false),
  ('trousers-pantalon-homme-velours-cotele-pantalon-droit', 'Pantalon Homme Velours Cotele Pantalon Droit', 'Pantalon Homme Velours Cotele Pantalon Droit', 'trousers', 5000, true, false),
  ('trousers-specifications-pantalones-de-mujer-pantalones-de', 'Specifications Pantalones De Mujer Pantalones De', 'Specifications Pantalones De Mujer Pantalones De', 'trousers', 4000, true, false),
  ('trousers-spring-autumn-smart-jeans-business-fashion', 'Spring Autumn Smart Jeans Business Fashion', 'Spring Autumn Smart Jeans Business Fashion', 'trousers', 6500, true, false),
  ('trousers-straight-fit-fits-with-slight-ease-through-hip', 'Straight Fit Fits With Slight Ease Through Hip', 'Straight Fit Fits With Slight Ease Through Hip', 'trousers', 8000, true, false),
  ('trousers-straight-fit-fitted-through-the-hip-and-thigh', 'Straight Fit Fitted Through The Hip And Thigh', 'Straight Fit Fitted Through The Hip And Thigh', 'trousers', 6000, true, false),
  ('trousers-the-rockford-comfort-fit-jeans-from-the-duke', 'The Rockford Comfort Fit Jeans From The Duke', 'The Rockford Comfort Fit Jeans From The Duke', 'trousers', 7000, true, false),
  ('trousers-title-white-textured-short-sleeve-shirt-and-pants', 'Title White Textured Short Sleeve Shirt And Pants', 'Title White Textured Short Sleeve Shirt And Pants', 'trousers', 7000, true, false),
  ('trousers-we-found-the-most-perfectly-engineered-denim-and', 'We Found The Most Perfectly Engineered Denim And', 'We Found The Most Perfectly Engineered Denim And', 'trousers', 6000, true, false),
  ('trousers-zegna-cotton-wool-trousers-neutrals-farfetch', 'Zegna Cotton Wool Trousers Neutrals Farfetch', 'Zegna Cotton Wool Trousers Neutrals Farfetch', 'trousers', 5500, true, false),
  ('cat-belts', 'Belts', 'Belts', 'belts', 1500, true, false),
  ('cat-casual', 'Casual', 'Casual', 'casual', 4500, true, false),
  ('cat-formal', 'Formal', 'Formal', 'formal', 19000, true, false),
  ('cat-shirts', 'Shirts', 'Shirts', 'shirts', 5500, true, false),
  ('cat-shoes', 'Shoes', 'Shoes', 'shoes', 15500, true, false),
  ('cat-socks', 'Socks', 'Socks', 'socks', 500, true, false),
  ('cat-sportswear', 'Sportswear', 'Sportswear', 'sportswear', 4000, true, false),
  ('cat-suits', 'Suits', 'Suits', 'suits', 18000, true, false),
  ('cat-trousers', 'Trousers', 'Trousers', 'trousers', 4500, true, false),
  ('hero-suit', 'Suit', 'Suit', 'formal', 16000, true, false)
)
insert into public.products (slug, title, description, category_id, price, sale_price, is_published, is_featured)
select
  pr.slug,
  pr.title,
  pr.description,
  c.id,
  pr.price,
  null,
  pr.is_published,
  pr.is_featured
from product_rows pr
left join public.categories c on c.slug = pr.category_slug
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  price = excluded.price,
  is_published = excluded.is_published;

with image_rows(product_slug, image_url, display_order) as (
  values
  ('belts-1-belt-2-colors-pay-for-one-belt-but-get-two', '/src/assets/catalog/belts/belts-1-belt-2-colors-pay-for-one-belt-but-get-two.jfif', 0),
  ('belts-1-belt-2-colors-smart-brown-on-one-side-classic', '/src/assets/catalog/belts/belts-1-belt-2-colors-smart-brown-on-one-side-classic.jfif', 0),
  ('belts-always-fit-this-woven-stretch-braided-belt-enable', '/src/assets/catalog/belts/belts-always-fit-this-woven-stretch-braided-belt-enable.jfif', 0),
  ('belts-antique-metal-buckle-cowhide-leather-belt-crafted', '/src/assets/catalog/belts/belts-antique-metal-buckle-cowhide-leather-belt-crafted.jfif', 0),
  ('belts-brand-lcg-luchengyi-buckle-material-alloy', '/src/assets/catalog/belts/belts-brand-lcg-luchengyi-buckle-material-alloy.jfif', 0),
  ('belts-brand-name-kavenpeterdepartment-name-adultbelts', '/src/assets/catalog/belts/belts-brand-name-kavenpeterdepartment-name-adultbelts.jfif', 0),
  ('belts-cat-belts', '/src/assets/catalog/belts/belts-cat-belts.jpg', 0),
  ('belts-cowather', '/src/assets/catalog/belts/belts-cowather.jfif', 0),
  ('belts-custom-size-fit-never-worry-about-the-belt-being', '/src/assets/catalog/belts/belts-custom-size-fit-never-worry-about-the-belt-being.jfif', 0),
  ('belts-embossed-western-cowboy-thick-belt-crafted-from', '/src/assets/catalog/belts/belts-embossed-western-cowboy-thick-belt-crafted-from.jfif', 0),
  ('belts-exact-fit-micro-adjustment-of-0-25-ensure-a', '/src/assets/catalog/belts/belts-exact-fit-micro-adjustment-of-0-25-ensure-a.jfif', 0),
  ('belts-for-exact-fit-leather-belts-for-men-allows-for', '/src/assets/catalog/belts/belts-for-exact-fit-leather-belts-for-men-allows-for.jfif', 0),
  ('belts-genuine-leather-belt-exaxt-fit-by-cutting-for-2', '/src/assets/catalog/belts/belts-genuine-leather-belt-exaxt-fit-by-cutting-for-2.jfif', 0),
  ('belts-genuine-leather-belt-exaxt-fit-by-cutting-for', '/src/assets/catalog/belts/belts-genuine-leather-belt-exaxt-fit-by-cutting-for.jfif', 0),
  ('belts-introducing-designers-casual-patchwork-men-belts', '/src/assets/catalog/belts/belts-introducing-designers-casual-patchwork-men-belts.jfif', 0),
  ('belts-item', '/src/assets/catalog/belts/belts-item.jfif', 0),
  ('belts-levi-s-men-s-leather-belt-with-plaque-buckle', '/src/assets/catalog/belts/belts-levi-s-men-s-leather-belt-with-plaque-buckle.jfif', 0),
  ('belts-luxury-designer-34mm-belts-men-high-quality-canvas', '/src/assets/catalog/belts/belts-luxury-designer-34mm-belts-men-high-quality-canvas.jfif', 0),
  ('belts-new-width-3-4cm-men-s-belt-business-formal-real', '/src/assets/catalog/belts/belts-new-width-3-4cm-men-s-belt-business-formal-real.jfif', 0),
  ('belts-premium-leather-the-kemisant-men-golf-belt-is', '/src/assets/catalog/belts/belts-premium-leather-the-kemisant-men-golf-belt-is.jfif', 0),
  ('belts-premium-quality-100-pure-genuine-leather-belt', '/src/assets/catalog/belts/belts-premium-quality-100-pure-genuine-leather-belt.jfif', 0),
  ('belts-specificationsbelt-width-4-3belts-material', '/src/assets/catalog/belts/belts-specificationsbelt-width-4-3belts-material.jfif', 0),
  ('belts-this-classic-men-s-brown-leather-belt-is-crafted', '/src/assets/catalog/belts/belts-this-classic-men-s-brown-leather-belt-is-crafted.jfif', 0),
  ('belts-top-genuine-leather-and-cowhide-material-men-s', '/src/assets/catalog/belts/belts-top-genuine-leather-and-cowhide-material-men-s.jfif', 0),
  ('khaki-pants-amazon-com-lapg-men-s-core-cargo-tactical-pants-2', '/src/assets/catalog/khaki-pants/khaki-pants-amazon-com-lapg-men-s-core-cargo-tactical-pants-2.jfif', 0),
  ('khaki-pants-amazon-com-lapg-men-s-core-cargo-tactical-pants', '/src/assets/catalog/khaki-pants/khaki-pants-amazon-com-lapg-men-s-core-cargo-tactical-pants.jfif', 0),
  ('khaki-pants-cargohose-herren-fruhling-herbst-baumwolle', '/src/assets/catalog/khaki-pants/khaki-pants-cargohose-herren-fruhling-herbst-baumwolle.jfif', 0),
  ('khaki-pants-everyones-favorite-mens-casual-cargo-shorts', '/src/assets/catalog/khaki-pants/khaki-pants-everyones-favorite-mens-casual-cargo-shorts.jfif', 0),
  ('khaki-pants-men-s-cargo-shorts-shorts-leg-drawstring-6-pocket', '/src/assets/catalog/khaki-pants/khaki-pants-men-s-cargo-shorts-shorts-leg-drawstring-6-pocket.jfif', 0),
  ('khaki-pants-men-s-totem-shirt-button-up-shirt-long-sleeve-vintage-gothic-outdoor-h', '/src/assets/catalog/khaki-pants/khaki-pants-men-s-totem-shirt-button-up-shirt-long-sleeve-vintage-gothic-outdoor-h.jfif', 0),
  ('khaki-pants-short-de-travail-elastique-multi-poches-style', '/src/assets/catalog/khaki-pants/khaki-pants-short-de-travail-elastique-multi-poches-style.jfif', 0),
  ('khaki-pants-the-all-season-tactical-pants-deliver-top-tier', '/src/assets/catalog/khaki-pants/khaki-pants-the-all-season-tactical-pants-deliver-top-tier.jfif', 0),
  ('khaki-pants-these-easygoing-chinos-are-a-great-alternative-to', '/src/assets/catalog/khaki-pants/khaki-pants-these-easygoing-chinos-are-a-great-alternative-to.jfif', 0),
  ('shirts-bring-a-burst-of-colours-to-your-spring-wardrobe', '/src/assets/catalog/shirts/shirts-bring-a-burst-of-colours-to-your-spring-wardrobe.jfif', 0),
  ('shirts-bubblems', '/src/assets/catalog/shirts/shirts-bubblems.jfif', 0),
  ('shirts-chemise-en-denim-corentm-la-force-masculine', '/src/assets/catalog/shirts/shirts-chemise-en-denim-corentm-la-force-masculine.jfif', 0),
  ('shirts-coofandy-men-s-dress-shirt-long-sleeve-casual-button-down-shirts', '/src/assets/catalog/shirts/shirts-coofandy-men-s-dress-shirt-long-sleeve-casual-button-down-shirts.jfif', 0),
  ('shirts-download-12', '/src/assets/catalog/shirts/shirts-download-12.jfif', 0),
  ('shirts-download', '/src/assets/catalog/shirts/shirts-download.jfif', 0),
  ('shirts-floral-print-dress-hirt-1-piece', '/src/assets/catalog/shirts/shirts-floral-print-dress-hirt-1-piece.jfif', 0),
  ('shirts-laurent-monaco-chemise-decouvrez-un-nouvel', '/src/assets/catalog/shirts/shirts-laurent-monaco-chemise-decouvrez-un-nouvel.jfif', 0),
  ('shirts-laurent-monaco-chemise-rayee-pour-homme', '/src/assets/catalog/shirts/shirts-laurent-monaco-chemise-rayee-pour-homme.jfif', 0),
  ('shirts-material-polyester-fibershirts-type-casual', '/src/assets/catalog/shirts/shirts-material-polyester-fibershirts-type-casual.jfif', 0),
  ('shirts-men-pleated-decoration-button-up-shirt', '/src/assets/catalog/shirts/shirts-men-pleated-decoration-button-up-shirt.jfif', 0),
  ('shirts-men-s-dress-shirt-black-red-black-gray-sea', '/src/assets/catalog/shirts/shirts-men-s-dress-shirt-black-red-black-gray-sea.jfif', 0),
  ('shirts-men-s-dress-shirt-striped-shirt-button-down-shirt', '/src/assets/catalog/shirts/shirts-men-s-dress-shirt-striped-shirt-button-down-shirt.jfif', 0),
  ('shirts-men-s-shirt-dress-shirt-button-up-shirt-black-white-wine-royal-blue-lo', '/src/assets/catalog/shirts/shirts-men-s-shirt-dress-shirt-button-up-shirt-black-white-wine-royal-blue-lo.jfif', 0),
  ('shirts-morintm-polo-raye-classique-moderne', '/src/assets/catalog/shirts/shirts-morintm-polo-raye-classique-moderne.jfif', 0),
  ('shirts-oliver-long-sleeve-high-gloss-shirt', '/src/assets/catalog/shirts/shirts-oliver-long-sleeve-high-gloss-shirt.jfif', 0),
  ('shirts-prices-may-vary-100-polyester-button-closure-the-2', '/src/assets/catalog/shirts/shirts-prices-may-vary-100-polyester-button-closure-the-2.jfif', 0),
  ('shirts-prices-may-vary-100-polyester-button-closure-the-3', '/src/assets/catalog/shirts/shirts-prices-may-vary-100-polyester-button-closure-the-3.jfif', 0),
  ('shirts-prices-may-vary-100-polyester-button-closure-the-4', '/src/assets/catalog/shirts/shirts-prices-may-vary-100-polyester-button-closure-the-4.jfif', 0),
  ('shirts-prices-may-vary-100-polyester-button-closure-the-5', '/src/assets/catalog/shirts/shirts-prices-may-vary-100-polyester-button-closure-the-5.jfif', 0),
  ('shirts-prices-may-vary-100-polyester-button-closure-the', '/src/assets/catalog/shirts/shirts-prices-may-vary-100-polyester-button-closure-the.jfif', 0),
  ('shirts-prices-may-vary-100-polyester-button-closure', '/src/assets/catalog/shirts/shirts-prices-may-vary-100-polyester-button-closure.jfif', 0),
  ('shirts-prices-may-vary-high-quality-fabricthe-men', '/src/assets/catalog/shirts/shirts-prices-may-vary-high-quality-fabricthe-men.jfif', 0),
  ('shirts-prices-may-vary-polyester-65-viscose-35-button', '/src/assets/catalog/shirts/shirts-prices-may-vary-polyester-65-viscose-35-button.jfif', 0),
  ('shirts-product-id-4001153086977', '/src/assets/catalog/shirts/shirts-product-id-4001153086977.jfif', 0),
  ('shirts-red-collar-fabric-embellished-men', '/src/assets/catalog/shirts/shirts-red-collar-fabric-embellished-men.jfif', 0),
  ('shirts-rossi-roma-poloshirt-in-grobstrick-beige-3xl', '/src/assets/catalog/shirts/shirts-rossi-roma-poloshirt-in-grobstrick-beige-3xl.jfif', 0),
  ('shirts-zeroyaa-men-s-hipster-african-tribal-graphic-patchwork-design-slim-fit', '/src/assets/catalog/shirts/shirts-zeroyaa-men-s-hipster-african-tribal-graphic-patchwork-design-slim-fit.jfif', 0),
  ('shoes-cat-shoes', '/src/assets/catalog/shoes/shoes-cat-shoes.jpg', 0),
  ('shoes-classic-leather-dress-shoes-for-men', '/src/assets/catalog/shoes/shoes-classic-leather-dress-shoes-for-men.jfif', 0),
  ('shoes-download-10', '/src/assets/catalog/shoes/shoes-download-10.jfif', 0),
  ('shoes-download-11', '/src/assets/catalog/shoes/shoes-download-11.jfif', 0),
  ('shoes-download-2', '/src/assets/catalog/shoes/shoes-download-2.jfif', 0),
  ('shoes-download-4', '/src/assets/catalog/shoes/shoes-download-4.jfif', 0),
  ('shoes-download-5', '/src/assets/catalog/shoes/shoes-download-5.jfif', 0),
  ('shoes-download-6', '/src/assets/catalog/shoes/shoes-download-6.jfif', 0),
  ('shoes-download-7', '/src/assets/catalog/shoes/shoes-download-7.jfif', 0),
  ('shoes-download-8', '/src/assets/catalog/shoes/shoes-download-8.jfif', 0),
  ('shoes-download-9', '/src/assets/catalog/shoes/shoes-download-9.jfif', 0),
  ('shoes-herren-sport-jogging-schuhe-hip-hop-jogging', '/src/assets/catalog/shoes/shoes-herren-sport-jogging-schuhe-hip-hop-jogging.jfif', 0),
  ('shoes-ky', '/src/assets/catalog/shoes/shoes-ky.jfif', 0),
  ('shoes-luxury-men-leather-loafers-designer-tassels-brogue', '/src/assets/catalog/shoes/shoes-luxury-men-leather-loafers-designer-tassels-brogue.jfif', 0),
  ('shoes-men-s-colorful-pattern-design-loafers-with-shiny-elements-low-cut-slip', '/src/assets/catalog/shoes/shoes-men-s-colorful-pattern-design-loafers-with-shiny-elements-low-cut-slip.jfif', 0),
  ('shoes-shoes', '/src/assets/catalog/shoes/shoes-shoes.jfif', 0),
  ('shoes-stand-tall-stay-bold-the-chunky-heel', '/src/assets/catalog/shoes/shoes-stand-tall-stay-bold-the-chunky-heel.jfif', 0),
  ('shoes-temu-best-deals', '/src/assets/catalog/shoes/shoes-temu-best-deals.jfif', 0),
  ('shoes-the-first-step-to-perfection-shoes', '/src/assets/catalog/shoes/shoes-the-first-step-to-perfection-shoes.jfif', 0),
  ('shoes-this-item-is-unavailable-etsy', '/src/assets/catalog/shoes/shoes-this-item-is-unavailable-etsy.jfif', 0),
  ('socks-a-must-have-addition-to-every-man-s-winter', '/src/assets/catalog/socks/socks-a-must-have-addition-to-every-man-s-winter.jfif', 0),
  ('socks-best-socks-for-men-shop-for-mens-socks-online', '/src/assets/catalog/socks/socks-best-socks-for-men-shop-for-mens-socks-online.jfif', 0),
  ('socks-cat-socks-2', '/src/assets/catalog/socks/socks-cat-socks-2.jpg', 0),
  ('socks-hippih-5-pairs-men-dress-socks-cotton-argyle', '/src/assets/catalog/socks/socks-hippih-5-pairs-men-dress-socks-cotton-argyle.jfif', 0),
  ('socks-multicolorido-collar-tecido-simples-meias-de', '/src/assets/catalog/socks/socks-multicolorido-collar-tecido-simples-meias-de.jfif', 0),
  ('socks-qcwqmyl-men-s-grip-soccer-socks-anti-slip-hospital', '/src/assets/catalog/socks/socks-qcwqmyl-men-s-grip-soccer-socks-anti-slip-hospital.jfif', 0),
  ('socks-quality-materials-dress-socks-made-with-fine', '/src/assets/catalog/socks/socks-quality-materials-dress-socks-made-with-fine.jfif', 0),
  ('suits-attirez-lattention-deplacez-vous-avec-assurance', '/src/assets/catalog/suits/suits-attirez-lattention-deplacez-vous-avec-assurance.jfif', 0),
  ('suits-black-mandarin-collar-suit-gentleman-s-guru-2', '/src/assets/catalog/suits/suits-black-mandarin-collar-suit-gentleman-s-guru-2.jfif', 0),
  ('suits-black-mandarin-collar-suit-gentleman-s-guru', '/src/assets/catalog/suits/suits-black-mandarin-collar-suit-gentleman-s-guru.jfif', 0),
  ('suits-brown-houndstooth-3-piece-suit-for-men-double-2', '/src/assets/catalog/suits/suits-brown-houndstooth-3-piece-suit-for-men-double-2.jfif', 0),
  ('suits-brown-houndstooth-3-piece-suit-for-men-double-3', '/src/assets/catalog/suits/suits-brown-houndstooth-3-piece-suit-for-men-double-3.jfif', 0),
  ('suits-brown-houndstooth-3-piece-suit-for-men-double', '/src/assets/catalog/suits/suits-brown-houndstooth-3-piece-suit-for-men-double.jfif', 0),
  ('suits-cat-formal', '/src/assets/catalog/suits/suits-cat-formal.jpg', 0),
  ('suits-cat-suits', '/src/assets/catalog/suits/suits-cat-suits.jpg', 0),
  ('suits-choose-timeless-elegance-with-the-men-s-leather', '/src/assets/catalog/suits/suits-choose-timeless-elegance-with-the-men-s-leather.jfif', 0),
  ('suits-decouvrez-l-elegance-avec-le-modele-aaron-une', '/src/assets/catalog/suits/suits-decouvrez-l-elegance-avec-le-modele-aaron-une.jfif', 0),
  ('suits-description-formal-men-s-suits-2-piece-slim-fit', '/src/assets/catalog/suits/suits-description-formal-men-s-suits-2-piece-slim-fit.jfif', 0),
  ('suits-discover-aryan-dark-navy-three-pieces-close', '/src/assets/catalog/suits/suits-discover-aryan-dark-navy-three-pieces-close.jfif', 0),
  ('suits-discover-the-pinnacle-of-ready-to-wear-fashion', '/src/assets/catalog/suits/suits-discover-the-pinnacle-of-ready-to-wear-fashion.jfif', 0),
  ('suits-discover-the-very-best-kent-dark-green-3-pieces', '/src/assets/catalog/suits/suits-discover-the-very-best-kent-dark-green-3-pieces.jfif', 0),
  ('suits-elegance-tailored-with-intention-army-green-meets', '/src/assets/catalog/suits/suits-elegance-tailored-with-intention-army-green-meets.jfif', 0),
  ('suits-elevate-your-formal-style-with-this-luxurious', '/src/assets/catalog/suits/suits-elevate-your-formal-style-with-this-luxurious.jfif', 0),
  ('suits-formal-men-s-suits-2-piece-slim-fit-performance', '/src/assets/catalog/suits/suits-formal-men-s-suits-2-piece-slim-fit-performance.jfif', 0),
  ('suits-formelle-bekleidung-fur-besondere-anlasse', '/src/assets/catalog/suits/suits-formelle-bekleidung-fur-besondere-anlasse.jfif', 0),
  ('suits-hero-suit', '/src/assets/catalog/suits/suits-hero-suit.jpg', 0),
  ('suits-instagram-2', '/src/assets/catalog/suits/suits-instagram-2.jfif', 0),
  ('suits-jacket-regular-fit-single-breasted-notch', '/src/assets/catalog/suits/suits-jacket-regular-fit-single-breasted-notch.jfif', 0),
  ('suits-laurent-monaco-structure-sur-mesure-elegance', '/src/assets/catalog/suits/suits-laurent-monaco-structure-sur-mesure-elegance.jfif', 0),
  ('suits-looks-like-something-from-a-final-fantasy', '/src/assets/catalog/suits/suits-looks-like-something-from-a-final-fantasy.jfif', 0),
  ('suits-make-a-lasting-impression-with-this-men-s-slim-fit', '/src/assets/catalog/suits/suits-make-a-lasting-impression-with-this-men-s-slim-fit.jfif', 0),
  ('suits-men-s-grey-double-breasted-suit-timeless', '/src/assets/catalog/suits/suits-men-s-grey-double-breasted-suit-timeless.jfif', 0),
  ('suits-men-s-suits-slim-fit-3-pieces-notch-lapel-formal-2', '/src/assets/catalog/suits/suits-men-s-suits-slim-fit-3-pieces-notch-lapel-formal-2.jfif', 0),
  ('suits-men-s-suits-slim-fit-3-pieces-notch-lapel-formal', '/src/assets/catalog/suits/suits-men-s-suits-slim-fit-3-pieces-notch-lapel-formal.jfif', 0),
  ('suits-men-tie-sets-classic-fashion-necktie-set-with', '/src/assets/catalog/suits/suits-men-tie-sets-classic-fashion-necktie-set-with.jfif', 0),
  ('suits-mens-premium-black-2-piece-prom-suit-elegant-slim-fit-custom-wedding-g', '/src/assets/catalog/suits/suits-mens-premium-black-2-piece-prom-suit-elegant-slim-fit-custom-wedding-g.jfif', 0),
  ('suits-prices-may-vary-free-customizationcheck-out-the', '/src/assets/catalog/suits/suits-prices-may-vary-free-customizationcheck-out-the.jfif', 0),
  ('suits-redefine-morden-tailoring-with-this-two-tone', '/src/assets/catalog/suits/suits-redefine-morden-tailoring-with-this-two-tone.jfif', 0),
  ('suits-refined-timeless-and-effortlessly-elegant', '/src/assets/catalog/suits/suits-refined-timeless-and-effortlessly-elegant.jfif', 0),
  ('suits-rockefeller-collection-double-breasted-stripe', '/src/assets/catalog/suits/suits-rockefeller-collection-double-breasted-stripe.jfif', 0),
  ('suits-royal-blue-tuxedo-with-black-lapel-gentleman-s', '/src/assets/catalog/suits/suits-royal-blue-tuxedo-with-black-lapel-gentleman-s.jfif', 0),
  ('suits-step-into-timeless-elegance-with-this-men-s-navy', '/src/assets/catalog/suits/suits-step-into-timeless-elegance-with-this-men-s-navy.jfif', 0),
  ('suits-this-garment-portrays-all-the-original-styling-of', '/src/assets/catalog/suits/suits-this-garment-portrays-all-the-original-styling-of.jfif', 0),
  ('suits-top-offer-of-the-season-men-s-luxury-designer', '/src/assets/catalog/suits/suits-top-offer-of-the-season-men-s-luxury-designer.jfif', 0),
  ('suits-upgrade-your-professional-wardrobe-with-our-men-s', '/src/assets/catalog/suits/suits-upgrade-your-professional-wardrobe-with-our-men-s.jfif', 0),
  ('suits-vintage-plaid-tweed-three-pieces-suit-elevate-your', '/src/assets/catalog/suits/suits-vintage-plaid-tweed-three-pieces-suit-elevate-your.jfif', 0),
  ('suits-wangyue-men-s-chinese-tunic-suit-stand-collar-slim', '/src/assets/catalog/suits/suits-wangyue-men-s-chinese-tunic-suit-stand-collar-slim.jfif', 0),
  ('t-shirts-black-casual-collar-short-sleeve', '/src/assets/catalog/t-shirts/t-shirts-black-casual-collar-short-sleeve.jfif', 0),
  ('t-shirts-casual-top-from-build-your-brand-comfortable', '/src/assets/catalog/t-shirts/t-shirts-casual-top-from-build-your-brand-comfortable.jfif', 0),
  ('t-shirts-cat-casual', '/src/assets/catalog/t-shirts/t-shirts-cat-casual.jpg', 0),
  ('t-shirts-cat-shirts', '/src/assets/catalog/t-shirts/t-shirts-cat-shirts.jpg', 0),
  ('t-shirts-category-t-shirt-season-summer-fabric-100', '/src/assets/catalog/t-shirts/t-shirts-category-t-shirt-season-summer-fabric-100.jfif', 0),
  ('t-shirts-dm-for-size-m-l-xl-2xl-i-also-provide-custom-logo', '/src/assets/catalog/t-shirts/t-shirts-dm-for-size-m-l-xl-2xl-i-also-provide-custom-logo.jfif', 0),
  ('t-shirts-instagram', '/src/assets/catalog/t-shirts/t-shirts-instagram.jfif', 0),
  ('t-shirts-men-allover-print-button-front-shirt', '/src/assets/catalog/t-shirts/t-shirts-men-allover-print-button-front-shirt.jfif', 0),
  ('t-shirts-men-argyle-print-shirt', '/src/assets/catalog/t-shirts/t-shirts-men-argyle-print-shirt.jfif', 0),
  ('t-shirts-men-random-geo-print-shirt-without-tee-slim-fit', '/src/assets/catalog/t-shirts/t-shirts-men-random-geo-print-shirt-without-tee-slim-fit.jfif', 0),
  ('t-shirts-men-slim-fit-shirt-long-sleeve-men-s-designer', '/src/assets/catalog/t-shirts/t-shirts-men-slim-fit-shirt-long-sleeve-men-s-designer.jfif', 0),
  ('t-shirts-men-t-shirts-fit-crew-neck-short-sleeve-casual', '/src/assets/catalog/t-shirts/t-shirts-men-t-shirts-fit-crew-neck-short-sleeve-casual.jfif', 0),
  ('t-shirts-neo-chrome-panel-boxy-tee-t-shirt-all-size', '/src/assets/catalog/t-shirts/t-shirts-neo-chrome-panel-boxy-tee-t-shirt-all-size.jfif', 0),
  ('t-shirts-prices-may-vary-60-cotton-40-polyester', '/src/assets/catalog/t-shirts/t-shirts-prices-may-vary-60-cotton-40-polyester.jfif', 0),
  ('t-shirts-ressentez-vous-bien-avec-un-style-quotidien-sans-2', '/src/assets/catalog/t-shirts/t-shirts-ressentez-vous-bien-avec-un-style-quotidien-sans-2.jfif', 0),
  ('t-shirts-ressentez-vous-bien-avec-un-style-quotidien-sans', '/src/assets/catalog/t-shirts/t-shirts-ressentez-vous-bien-avec-un-style-quotidien-sans.jfif', 0),
  ('t-shirts-stay-effortlessly-stylish-with-this-modern-color', '/src/assets/catalog/t-shirts/t-shirts-stay-effortlessly-stylish-with-this-modern-color.jfif', 0),
  ('t-shirts-upgrade-your-everyday-style-with-our-premium-men-s', '/src/assets/catalog/t-shirts/t-shirts-upgrade-your-everyday-style-with-our-premium-men-s.jfif', 0),
  ('t-shirts-veredeln-sie-ihre-freizeitoutfits-mit-dem', '/src/assets/catalog/t-shirts/t-shirts-veredeln-sie-ihre-freizeitoutfits-mit-dem.jfif', 0),
  ('track-suits-cat-sportswear', '/src/assets/catalog/track-suits/track-suits-cat-sportswear.jpg', 0),
  ('track-suits-conjunto-de-agasalho-esportivo-masculino-com', '/src/assets/catalog/track-suits/track-suits-conjunto-de-agasalho-esportivo-masculino-com.jfif', 0),
  ('track-suits-deportivo-in-2022-designer-clothes-for-men-men', '/src/assets/catalog/track-suits/track-suits-deportivo-in-2022-designer-clothes-for-men-men.jfif', 0),
  ('track-suits-download-3', '/src/assets/catalog/track-suits/track-suits-download-3.jfif', 0),
  ('track-suits-item-2', '/src/assets/catalog/track-suits/track-suits-item-2.jfif', 0),
  ('track-suits-jawin-premium-waffle-tracksuit-hoodie-fabric', '/src/assets/catalog/track-suits/track-suits-jawin-premium-waffle-tracksuit-hoodie-fabric.jfif', 0),
  ('track-suits-men-s-european-and-american-colorblock-hoodie', '/src/assets/catalog/track-suits/track-suits-men-s-european-and-american-colorblock-hoodie.jfif', 0),
  ('track-suits-men-s-tracksuits-track-suits-sets-jogging-suits', '/src/assets/catalog/track-suits/track-suits-men-s-tracksuits-track-suits-sets-jogging-suits.jfif', 0),
  ('track-suits-mens-track-suits-2-piece-the-track-suit-consists', '/src/assets/catalog/track-suits/track-suits-mens-track-suits-2-piece-the-track-suit-consists.jfif', 0),
  ('track-suits-price-product-description-item', '/src/assets/catalog/track-suits/track-suits-price-product-description-item.jfif', 0),
  ('track-suits-prices-may-vary-polyester-cotton-drawstring-2', '/src/assets/catalog/track-suits/track-suits-prices-may-vary-polyester-cotton-drawstring-2.jfif', 0),
  ('track-suits-prices-may-vary-polyester-cotton-drawstring', '/src/assets/catalog/track-suits/track-suits-prices-may-vary-polyester-cotton-drawstring.jfif', 0),
  ('track-suits-product-information-materials-90-polyester-10', '/src/assets/catalog/track-suits/track-suits-product-information-materials-90-polyester-10.jfif', 0),
  ('track-suits-season-winter-fall-fabric-polyester-sleeve', '/src/assets/catalog/track-suits/track-suits-season-winter-fall-fabric-polyester-sleeve.jfif', 0),
  ('track-suits-service-if-you-have-any-question-please-feel', '/src/assets/catalog/track-suits/track-suits-service-if-you-have-any-question-please-feel.jfif', 0),
  ('track-suits-shein', '/src/assets/catalog/track-suits/track-suits-shein.jfif', 0),
  ('track-suits-source-new-jogging-custom-track-suits-tracksuit', '/src/assets/catalog/track-suits/track-suits-source-new-jogging-custom-track-suits-tracksuit.jfif', 0),
  ('track-suits-tbmpoy-size-m-men-s-tracksuit-athletic-sports', '/src/assets/catalog/track-suits/track-suits-tbmpoy-size-m-men-s-tracksuit-athletic-sports.jfif', 0),
  ('track-suits-track-suits-for-men-set-full-zip-active-athletic', '/src/assets/catalog/track-suits/track-suits-track-suits-for-men-set-full-zip-active-athletic.jfif', 0),
  ('track-suits-tracksuits-are-now-in-the-mainstream-fashion', '/src/assets/catalog/track-suits/track-suits-tracksuits-are-now-in-the-mainstream-fashion.jfif', 0),
  ('track-suits-women-s-zipper-sports-suit-athletic-tracksuit', '/src/assets/catalog/track-suits/track-suits-women-s-zipper-sports-suit-athletic-tracksuit.jfif', 0),
  ('trousers-brand-name-icpansmodel-number-xk058material', '/src/assets/catalog/trousers/trousers-brand-name-icpansmodel-number-xk058material.jfif', 0),
  ('trousers-casual-fashion-sweatshirts-jackets-pants-plus-size', '/src/assets/catalog/trousers/trousers-casual-fashion-sweatshirts-jackets-pants-plus-size.jfif', 0),
  ('trousers-cat-trousers', '/src/assets/catalog/trousers/trousers-cat-trousers.jpg', 0),
  ('trousers-cedratm-classic-denim-jeans-appear-confident-with', '/src/assets/catalog/trousers/trousers-cedratm-classic-denim-jeans-appear-confident-with.jfif', 0),
  ('trousers-classic-fit-generous-fit-through-the-hip-and', '/src/assets/catalog/trousers/trousers-classic-fit-generous-fit-through-the-hip-and.jfif', 0),
  ('trousers-fiabilite-quotidienne-les-pantalons-ferraro-en', '/src/assets/catalog/trousers/trousers-fiabilite-quotidienne-les-pantalons-ferraro-en.jfif', 0),
  ('trousers-jeans-men-new-men-s-fashion-business-jeans-classic', '/src/assets/catalog/trousers/trousers-jeans-men-new-men-s-fashion-business-jeans-classic.jfif', 0),
  ('trousers-mens-cotton-blend-waffle-trousers-straight', '/src/assets/catalog/trousers/trousers-mens-cotton-blend-waffle-trousers-straight.jfif', 0),
  ('trousers-mens-formal-wear-trousers-plain-colours-by-cavani-2', '/src/assets/catalog/trousers/trousers-mens-formal-wear-trousers-plain-colours-by-cavani-2.jfif', 0),
  ('trousers-mens-formal-wear-trousers-plain-colours-by-cavani', '/src/assets/catalog/trousers/trousers-mens-formal-wear-trousers-plain-colours-by-cavani.jfif', 0),
  ('trousers-mens-summer-suit-pants-thin-elastic-straight', '/src/assets/catalog/trousers/trousers-mens-summer-suit-pants-thin-elastic-straight.jfif', 0),
  ('trousers-okonkwo-style-americain-vintage-pantalon-militaire', '/src/assets/catalog/trousers/trousers-okonkwo-style-americain-vintage-pantalon-militaire.jfif', 0),
  ('trousers-pantalon-homme-velours-cotele-pantalon-droit', '/src/assets/catalog/trousers/trousers-pantalon-homme-velours-cotele-pantalon-droit.jfif', 0),
  ('trousers-specifications-pantalones-de-mujer-pantalones-de', '/src/assets/catalog/trousers/trousers-specifications-pantalones-de-mujer-pantalones-de.jfif', 0),
  ('trousers-spring-autumn-smart-jeans-business-fashion', '/src/assets/catalog/trousers/trousers-spring-autumn-smart-jeans-business-fashion.jfif', 0),
  ('trousers-straight-fit-fits-with-slight-ease-through-hip', '/src/assets/catalog/trousers/trousers-straight-fit-fits-with-slight-ease-through-hip.jfif', 0),
  ('trousers-straight-fit-fitted-through-the-hip-and-thigh', '/src/assets/catalog/trousers/trousers-straight-fit-fitted-through-the-hip-and-thigh.jfif', 0),
  ('trousers-the-rockford-comfort-fit-jeans-from-the-duke', '/src/assets/catalog/trousers/trousers-the-rockford-comfort-fit-jeans-from-the-duke.jfif', 0),
  ('trousers-title-white-textured-short-sleeve-shirt-and-pants', '/src/assets/catalog/trousers/trousers-title-white-textured-short-sleeve-shirt-and-pants.jfif', 0),
  ('trousers-we-found-the-most-perfectly-engineered-denim-and', '/src/assets/catalog/trousers/trousers-we-found-the-most-perfectly-engineered-denim-and.jfif', 0),
  ('trousers-zegna-cotton-wool-trousers-neutrals-farfetch', '/src/assets/catalog/trousers/trousers-zegna-cotton-wool-trousers-neutrals-farfetch.jfif', 0),
  ('cat-belts', '/src/assets/cat-belts.jpg', 0),
  ('cat-casual', '/src/assets/cat-casual.jpg', 0),
  ('cat-formal', '/src/assets/cat-formal.jpg', 0),
  ('cat-shirts', '/src/assets/cat-shirts.jpg', 0),
  ('cat-shoes', '/src/assets/cat-shoes.jpg', 0),
  ('cat-socks', '/src/assets/cat-socks.jpg', 0),
  ('cat-sportswear', '/src/assets/cat-sportswear.jpg', 0),
  ('cat-suits', '/src/assets/cat-suits.jpg', 0),
  ('cat-trousers', '/src/assets/cat-trousers.jpg', 0),
  ('hero-suit', '/src/assets/hero-suit.jpg', 0)
)
insert into public.product_images (product_id, image_url, display_order)
select p.id, ir.image_url, ir.display_order
from image_rows ir
join public.products p on p.slug = ir.product_slug
where not exists (
  select 1
  from public.product_images pi
  where pi.product_id = p.id
    and pi.image_url = ir.image_url
);

commit;
